apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      imagePullSecrets:
      - name: regcred
      volumes:
      - name: static-volume
        persistentVolumeClaim:
          claimName: backend-pvc
      - name: django-config
        configMap:
          name: django-config-file
      containers:
      - name: backend
        image: unlimitedbiking/review-backend
        volumeMounts:
        - mountPath: "/home/app/web/staticfiles"
          name: static-volume
        - mountPath: "/home/app/web/ubms/.env"
          name: django-config
          subPath: ".env"
        args: ["gunicorn", "ubms.wsgi:application", "--bind", "0.0.0.0:8000"]
        ports:
        - containerPort: 8000
        env:
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: postgres-configmap
              key: database_url
        - name: POSTGRES_PORT
          valueFrom:
            configMapKeyRef:
              name: postgres-configmap
              key: database_port
        - name: POSTGRES_DB
          value: ubms
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-password