apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config-file
data:
  default.conf: |
    upstream backend {
        server backend-service:8000;
    }

    server {
        listen 80;

        server_name dev.unlimitedbiking.com;

        location / {
            proxy_pass http://backend;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Host $host;
            proxy_redirect off;
        }


        location /static/ {
            alias /home/app/web/staticfiles/;
        }
    }

    server {
        listen       80;

        server_name app.unlimitedbiking.com;

        location / {
          root   /usr/share/nginx/html;
          index  index.html;
          try_files $uri $uri/ /index.html;
        }
    }